<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fgd</string>
	</array>
	<key>name</key>
	<string>Forge Game Data (.fgd)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.fgd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@include</string>
			<key>name</key>
			<string>keyword.control.import.include.fgd</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.fgd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(axis|angle|color255|color1|filterclass|material|node_dest|npcclass|origin|pointentityclass|scene|sidelist|sound|sprite|studio|target_destination|target_name_or_class|target_source|vecline|vector)\b</string>
			<key>name</key>
			<string>keyword.fgd</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fgd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fgd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.begin.fgd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fgd</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.end.fgd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(input|output) ([A-Z][^(]*)(\()([^)]*)(\)) (:)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@(BaseClass|PointClass|NPCClass|SolidClass|KeyFrameClass|MoveClass|FilterClass)</string>
			<key>name</key>
			<string>entity.name.class.fgd</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fgd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fgd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(base|color|iconsprite|sphere|studio|studioprop|line|frustum|size)\(([^)]*)\)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.fgd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fgd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(=) (\w+)\s*(\:)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.forge-game-data</string>
	<key>uuid</key>
	<string>1f14ccb6-0cd6-4605-a0e8-d3a690e9a42c</string>
</dict>
</plist>
